package com.taf.data.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.taf.data.database.dao.DbPost;

import com.taf.data.database.dao.DbPostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbPostDaoConfig;

    private final DbPostDao dbPostDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbPostDaoConfig = daoConfigMap.get(DbPostDao.class).clone();
        dbPostDaoConfig.initIdentityScope(type);

        dbPostDao = new DbPostDao(dbPostDaoConfig, this);

        registerDao(DbPost.class, dbPostDao);
    }
    
    public void clear() {
        dbPostDaoConfig.getIdentityScope().clear();
    }

    public DbPostDao getDbPostDao() {
        return dbPostDao;
    }

}
