package com.taf.data.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.taf.data.database.dao.DbPost;
import com.taf.data.database.dao.DbCategory;
import com.taf.data.database.dao.DbSection;

import com.taf.data.database.dao.DbPostDao;
import com.taf.data.database.dao.DbCategoryDao;
import com.taf.data.database.dao.DbSectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbPostDaoConfig;
    private final DaoConfig dbCategoryDaoConfig;
    private final DaoConfig dbSectionDaoConfig;

    private final DbPostDao dbPostDao;
    private final DbCategoryDao dbCategoryDao;
    private final DbSectionDao dbSectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbPostDaoConfig = daoConfigMap.get(DbPostDao.class).clone();
        dbPostDaoConfig.initIdentityScope(type);

        dbCategoryDaoConfig = daoConfigMap.get(DbCategoryDao.class).clone();
        dbCategoryDaoConfig.initIdentityScope(type);

        dbSectionDaoConfig = daoConfigMap.get(DbSectionDao.class).clone();
        dbSectionDaoConfig.initIdentityScope(type);

        dbPostDao = new DbPostDao(dbPostDaoConfig, this);
        dbCategoryDao = new DbCategoryDao(dbCategoryDaoConfig, this);
        dbSectionDao = new DbSectionDao(dbSectionDaoConfig, this);

        registerDao(DbPost.class, dbPostDao);
        registerDao(DbCategory.class, dbCategoryDao);
        registerDao(DbSection.class, dbSectionDao);
    }
    
    public void clear() {
        dbPostDaoConfig.getIdentityScope().clear();
        dbCategoryDaoConfig.getIdentityScope().clear();
        dbSectionDaoConfig.getIdentityScope().clear();
    }

    public DbPostDao getDbPostDao() {
        return dbPostDao;
    }

    public DbCategoryDao getDbCategoryDao() {
        return dbCategoryDao;
    }

    public DbSectionDao getDbSectionDao() {
        return dbSectionDao;
    }

}
