package com.taf.data.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB_CATEGORY".
 */
public class DbCategory {

    private Long id;
    private String name;
    private String icon;
    private String detailImage;
    private String detailIcon;
    private Long parentId;
    private Long position;
    private Long categoryId;
    private String sectionName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DbCategory() {
    }

    public DbCategory(Long id) {
        this.id = id;
    }

    public DbCategory(Long id, String name, String icon, String detailImage, String detailIcon, Long parentId, Long position, Long categoryId, String sectionName) {
        this.id = id;
        this.name = name;
        this.icon = icon;
        this.detailImage = detailImage;
        this.detailIcon = detailIcon;
        this.parentId = parentId;
        this.position = position;
        this.categoryId = categoryId;
        this.sectionName = sectionName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getDetailImage() {
        return detailImage;
    }

    public void setDetailImage(String detailImage) {
        this.detailImage = detailImage;
    }

    public String getDetailIcon() {
        return detailIcon;
    }

    public void setDetailIcon(String detailIcon) {
        this.detailIcon = detailIcon;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getPosition() {
        return position;
    }

    public void setPosition(Long position) {
        this.position = position;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public String getSectionName() {
        return sectionName;
    }

    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
