package com.taf.data.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB_CATEGORY".
 */
public class DbCategory {

    private Long id;
    private String title;
    private String alias;
    private String parentAlias;
    private String iconUrl;
    private String smallIconUrl;
    private String coverImageUrl;
    private Integer leftIndex;
    private Integer rightIndex;
    private Integer depth;
    private Long parentId;
    private Long position;
    private Long createdAt;
    private Long updatedAt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DbCategory() {
    }

    public DbCategory(Long id) {
        this.id = id;
    }

    public DbCategory(Long id, String title, String alias, String parentAlias, String iconUrl, String smallIconUrl, String coverImageUrl, Integer leftIndex, Integer rightIndex, Integer depth, Long parentId, Long position, Long createdAt, Long updatedAt) {
        this.id = id;
        this.title = title;
        this.alias = alias;
        this.parentAlias = parentAlias;
        this.iconUrl = iconUrl;
        this.smallIconUrl = smallIconUrl;
        this.coverImageUrl = coverImageUrl;
        this.leftIndex = leftIndex;
        this.rightIndex = rightIndex;
        this.depth = depth;
        this.parentId = parentId;
        this.position = position;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getParentAlias() {
        return parentAlias;
    }

    public void setParentAlias(String parentAlias) {
        this.parentAlias = parentAlias;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public String getSmallIconUrl() {
        return smallIconUrl;
    }

    public void setSmallIconUrl(String smallIconUrl) {
        this.smallIconUrl = smallIconUrl;
    }

    public String getCoverImageUrl() {
        return coverImageUrl;
    }

    public void setCoverImageUrl(String coverImageUrl) {
        this.coverImageUrl = coverImageUrl;
    }

    public Integer getLeftIndex() {
        return leftIndex;
    }

    public void setLeftIndex(Integer leftIndex) {
        this.leftIndex = leftIndex;
    }

    public Integer getRightIndex() {
        return rightIndex;
    }

    public void setRightIndex(Integer rightIndex) {
        this.rightIndex = rightIndex;
    }

    public Integer getDepth() {
        return depth;
    }

    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getPosition() {
        return position;
    }

    public void setPosition(Long position) {
        this.position = position;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
