package com.taf.data.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.List;
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB_POST".
 */
public class DbPost {

    private Long id;
    private String title;
    private String description;
    private String type;
    private String data;
    private String source;
    private String tags;
    private Long createdAt;
    private Long updatedAt;
    private Integer favouriteCount;
    private Integer shareCount;
    private Boolean isFavourite;
    private Boolean isSynced;
    private Boolean isDownloaded;
    private Long downloadReference;
    private Integer viewCount;
    private Integer unsyncedViewCount;
    private String featuredImage;
    private Integer unsyncedShareCount;

    // KEEP FIELDS - put your custom fields here
    List<DbCategory> categoryList;
    // KEEP FIELDS END

    public DbPost() {
    }

    public DbPost(Long id) {
        this.id = id;
    }

    public DbPost(Long id, String title, String description, String type, String data, String source, String tags, Long createdAt, Long updatedAt, Integer favouriteCount, Integer shareCount, Boolean isFavourite, Boolean isSynced, Boolean isDownloaded, Long downloadReference, Integer viewCount, Integer unsyncedViewCount, String featuredImage, Integer unsyncedShareCount) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.type = type;
        this.data = data;
        this.source = source;
        this.tags = tags;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.favouriteCount = favouriteCount;
        this.shareCount = shareCount;
        this.isFavourite = isFavourite;
        this.isSynced = isSynced;
        this.isDownloaded = isDownloaded;
        this.downloadReference = downloadReference;
        this.viewCount = viewCount;
        this.unsyncedViewCount = unsyncedViewCount;
        this.featuredImage = featuredImage;
        this.unsyncedShareCount = unsyncedShareCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public Long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public Long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getFavouriteCount() {
        return favouriteCount;
    }

    public void setFavouriteCount(Integer favouriteCount) {
        this.favouriteCount = favouriteCount;
    }

    public Integer getShareCount() {
        return shareCount;
    }

    public void setShareCount(Integer shareCount) {
        this.shareCount = shareCount;
    }

    public Boolean getIsFavourite() {
        return isFavourite;
    }

    public void setIsFavourite(Boolean isFavourite) {
        this.isFavourite = isFavourite;
    }

    public Boolean getIsSynced() {
        return isSynced;
    }

    public void setIsSynced(Boolean isSynced) {
        this.isSynced = isSynced;
    }

    public Boolean getIsDownloaded() {
        return isDownloaded;
    }

    public void setIsDownloaded(Boolean isDownloaded) {
        this.isDownloaded = isDownloaded;
    }

    public Long getDownloadReference() {
        return downloadReference;
    }

    public void setDownloadReference(Long downloadReference) {
        this.downloadReference = downloadReference;
    }

    public Integer getViewCount() {
        return viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    public Integer getUnsyncedViewCount() {
        return unsyncedViewCount;
    }

    public void setUnsyncedViewCount(Integer unsyncedViewCount) {
        this.unsyncedViewCount = unsyncedViewCount;
    }

    public String getFeaturedImage() {
        return featuredImage;
    }

    public void setFeaturedImage(String featuredImage) {
        this.featuredImage = featuredImage;
    }

    public Integer getUnsyncedShareCount() {
        return unsyncedShareCount;
    }

    public void setUnsyncedShareCount(Integer unsyncedShareCount) {
        this.unsyncedShareCount = unsyncedShareCount;
    }

    // KEEP METHODS - put your custom methods here

    public List<DbCategory> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<DbCategory> pCategoryList) {
        categoryList = pCategoryList;
    }
    // KEEP METHODS END

}
