package com.taf.data.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.taf.data.database.dao.DbPost;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_POST".
*/
public class DbPostDao extends AbstractDao<DbPost, Long> {

    public static final String TABLENAME = "DB_POST";

    /**
     * Properties of entity DbPost.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Description = new Property(2, String.class, "description", false, "DESCRIPTION");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property Data = new Property(4, String.class, "data", false, "DATA");
        public final static Property Source = new Property(5, String.class, "source", false, "SOURCE");
        public final static Property Tags = new Property(6, String.class, "tags", false, "TAGS");
        public final static Property CreatedAt = new Property(7, Long.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(8, Long.class, "updatedAt", false, "UPDATED_AT");
        public final static Property FavouriteCount = new Property(9, Integer.class, "favouriteCount", false, "FAVOURITE_COUNT");
        public final static Property ShareCount = new Property(10, Integer.class, "shareCount", false, "SHARE_COUNT");
        public final static Property IsFavourite = new Property(11, Boolean.class, "isFavourite", false, "IS_FAVOURITE");
        public final static Property IsSynced = new Property(12, Boolean.class, "isSynced", false, "IS_SYNCED");
        public final static Property IsDownloaded = new Property(13, Boolean.class, "isDownloaded", false, "IS_DOWNLOADED");
        public final static Property DownloadReference = new Property(14, Long.class, "downloadReference", false, "DOWNLOAD_REFERENCE");
    };


    public DbPostDao(DaoConfig config) {
        super(config);
    }
    
    public DbPostDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_POST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"DESCRIPTION\" TEXT," + // 2: description
                "\"TYPE\" TEXT," + // 3: type
                "\"DATA\" TEXT," + // 4: data
                "\"SOURCE\" TEXT," + // 5: source
                "\"TAGS\" TEXT," + // 6: tags
                "\"CREATED_AT\" INTEGER," + // 7: createdAt
                "\"UPDATED_AT\" INTEGER," + // 8: updatedAt
                "\"FAVOURITE_COUNT\" INTEGER," + // 9: favouriteCount
                "\"SHARE_COUNT\" INTEGER," + // 10: shareCount
                "\"IS_FAVOURITE\" INTEGER," + // 11: isFavourite
                "\"IS_SYNCED\" INTEGER," + // 12: isSynced
                "\"IS_DOWNLOADED\" INTEGER," + // 13: isDownloaded
                "\"DOWNLOAD_REFERENCE\" INTEGER);"); // 14: downloadReference
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_POST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbPost entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(3, description);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        String data = entity.getData();
        if (data != null) {
            stmt.bindString(5, data);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(6, source);
        }
 
        String tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(7, tags);
        }
 
        Long createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(8, createdAt);
        }
 
        Long updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(9, updatedAt);
        }
 
        Integer favouriteCount = entity.getFavouriteCount();
        if (favouriteCount != null) {
            stmt.bindLong(10, favouriteCount);
        }
 
        Integer shareCount = entity.getShareCount();
        if (shareCount != null) {
            stmt.bindLong(11, shareCount);
        }
 
        Boolean isFavourite = entity.getIsFavourite();
        if (isFavourite != null) {
            stmt.bindLong(12, isFavourite ? 1L: 0L);
        }
 
        Boolean isSynced = entity.getIsSynced();
        if (isSynced != null) {
            stmt.bindLong(13, isSynced ? 1L: 0L);
        }
 
        Boolean isDownloaded = entity.getIsDownloaded();
        if (isDownloaded != null) {
            stmt.bindLong(14, isDownloaded ? 1L: 0L);
        }
 
        Long downloadReference = entity.getDownloadReference();
        if (downloadReference != null) {
            stmt.bindLong(15, downloadReference);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbPost readEntity(Cursor cursor, int offset) {
        DbPost entity = new DbPost( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // data
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // source
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tags
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // createdAt
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // updatedAt
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // favouriteCount
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // shareCount
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isFavourite
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isSynced
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // isDownloaded
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14) // downloadReference
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbPost entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setData(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSource(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTags(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCreatedAt(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setUpdatedAt(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setFavouriteCount(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setShareCount(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setIsFavourite(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setIsSynced(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setIsDownloaded(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setDownloadReference(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbPost entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbPost entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
