package com.taf.data.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB_POST_CATEGORY".
 */
public class DbPostCategory {

    private Long id;
    private Long postId;
    private Long categoryId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DbPostCategory() {
    }

    public DbPostCategory(Long id) {
        this.id = id;
    }

    public DbPostCategory(Long id, Long postId, Long categoryId) {
        this.id = id;
        this.postId = postId;
        this.categoryId = categoryId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPostId() {
        return postId;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
