package com.taf.data.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DB_SECTION".
 */
public class DbSection {

    private Long id;
    private Long sectionId;
    private String name;
    private String display_name;

    public DbSection() {
    }

    public DbSection(Long id) {
        this.id = id;
    }

    public DbSection(Long id, Long sectionId, String name, String display_name) {
        this.id = id;
        this.sectionId = sectionId;
        this.name = name;
        this.display_name = display_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSectionId() {
        return sectionId;
    }

    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDisplay_name() {
        return display_name;
    }

    public void setDisplay_name(String display_name) {
        this.display_name = display_name;
    }

}
