package com.taf.data.database.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DB_UN_SYNCED".
 */
public class DbUnSynced {

    private Long id;
    private Boolean favouriteStatus;
    private Integer shareCount;
    private Boolean syncedStatus;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DbUnSynced() {
    }

    public DbUnSynced(Long id) {
        this.id = id;
    }

    public DbUnSynced(Long id, Boolean favouriteStatus, Integer shareCount, Boolean syncedStatus) {
        this.id = id;
        this.favouriteStatus = favouriteStatus;
        this.shareCount = shareCount;
        this.syncedStatus = syncedStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getFavouriteStatus() {
        return favouriteStatus;
    }

    public void setFavouriteStatus(Boolean favouriteStatus) {
        this.favouriteStatus = favouriteStatus;
    }

    public Integer getShareCount() {
        return shareCount;
    }

    public void setShareCount(Integer shareCount) {
        this.shareCount = shareCount;
    }

    public Boolean getSyncedStatus() {
        return syncedStatus;
    }

    public void setSyncedStatus(Boolean syncedStatus) {
        this.syncedStatus = syncedStatus;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
